# On every push this script is executed
on:
  push:
    branches: [ 'main' ]

name: Build and deploy GH Pages
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Install zola
        run: sudo snap install --edge zola
      - name: Build site
        run: zola build
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: gh-pages
          FOLDER: public/
