# On every push this script is executed
on:
  push:
    branches: [ 'main' ]

name: Build and deploy GH Pages
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      # Build & deploy
      - name: Deploy to gh-pages branch
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ github.token }}
